### ISSUE TITLE
range-v3 build issue with clang and gcc 6.1.1 headers

### ISSUE THREAD

**Issue by shaharv** [ericniebler/range-v3#466]
range-v3 fails to build with clang and gcc-6.1.1 headers. When changing to gcc 5.4.0 headers, it's fine. In particular, sort.cpp fails to compile with an error coming from gcc's stl_pair.h.
This happens with both clang-3.8 and clang trunk version.

The error could be reproduced with the following command line:
    _/usr/bin/clang++-3.8 -I../include -std=c++14 -c ../test/algorithm/sort.cpp_

The error message (abbreviated since it's very long):
_In file included from ../test/algorithm/sort.cpp:22:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/memory:62:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algobase.h:64:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_pair.h:215:29: error: call to deleted constructor of
      '(anonymous namespace)::Int'
        : first(__p.first), second(__p.second) { }
                            ^      ~~~~~~~~~~
../include/range/v3/utility/common_type.hpp:76:47: note: in instantiation of function template specialization 'std::pair<int,
      (anonymous namespace)::Int>::pair<int &, (anonymous namespace)::Int &, true>' requested here
            using _cond_res = decltype(true ? std::declval<T>() : std::declval<U>());
                                              ^_

Please find the full build log and build commands in attached.
Cheers

[build_range_log.zip](https://github.com/ericniebler/range-v3/files/455037/build_range_log.zip)
[build-range.sh.txt](https://github.com/ericniebler/range-v3/files/455040/build-range.sh.txt)

**Comment by ericniebler** [comment]
Thanks for the report.

**Comment by CaseyCarter** [comment]
This looks like a libstdc++ bug: the resolution of [PR 70437](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70437) broke the constraints on `pair`'s converting constructors. `pair<T, U>` now always claims to be constructible from `pair<V, W> const&` and `pair<V, W>&&` when `is_same_v<decay_t<T>, decay_t<V>> && is_same_v<decay_t<U>, decay_t<W>>`.

**Comment by ericniebler** [comment]
Crud. We could work around the issue with our own `is_constructible` that is specialized for `std::pair`. @CaseyCarter, did you file a bug against libstdc++?

**Comment by CaseyCarter** [comment]
No, I've been trying to determine the proper fix, so I haven't reported it yet.

**Comment by CaseyCarter** [comment]
Filed [GCC PR 77537](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77537) for the pair bug.

**Comment by CaseyCarter** [comment]
> We could work around the issue with our own `is_constructible` that is specialized for `std::pair`.

It would be easier to use `common_pair` instead of `std::pair` than to find every place that might perform a construction test and hijack it if it's checking `std::pair`.

**Comment by ericniebler** [comment]
> It would be easier to use `common_pair` instead of `std::pair` 

That's an interface-breaking change in some places

> than to find every place that might perform a construction test and hijack it if it's checking `std::pair`.

I was just thinking of s/`std::is_constructible`/`detail::is_constructible`/g, and then specializing `detail::is_constructible` on `std::pair`.

**Comment by CaseyCarter** [comment]
> I was just thinking of s/std::is_constructible/detail::is_constructible/g, and then specializing detail::is_constructible on std::pair.

`ConstructibleObject` tests a prvalue expression instead of using `is_constructible`, so that would miss all of the object concepts. For that matter, the OP triggers in the conditional operator inside `builtin_common_t`. We perform many different kinds of construction tests, and very few of them use `is_constructible`.

**Comment by CaseyCarter** [comment]
> That's an interface-breaking change in some places

The "danger zone" seems to be around `zip_view` iterators and `common_type`. I suspect we could avoid the issue by not letting `common_XXX` decay into `std::XXX` so easily.

**Comment by CaseyCarter** [comment]
>  I suspect we could avoid the issue by not letting `common_XXX` decay into `std::XXX` so easily.

You're forgetting that `common_XXX` inherits from `std::XXX`, so when the `std` types are broken, the range-v3 flavors are as well.

**Comment by CaseyCarter** [comment]
FYI, [PR 77537](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77537) has been fixed on trunk and for the next release of GCC6.

**Comment by ericniebler** [comment]
I'm closing this. I think it's better to wait for the fix from upstream than to make some intrusive hack around the bug.
