### ISSUE TITLE
how do you create a range of existing ranges?

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#547]
Say I have the following:
```c++
    std::string s{"ACGTTTATGTTTACGT"};

    auto v1 = ranges::view::all(s);
    auto v2 = ranges::view::reverse(s);

    auto combined = ranges::view::concat(v1, v2);
```
it will produce: `[A,C,G,T,T,T,A,T,G,T,T,T,A,C,G,T,T,G,C,A,T,T,T,G,T,A,T,T,T,G,C,A]`
However, what I want is `[[A,C,G,T,T,T,A,T,G,T,T,T,A,C,G,T],[T,G,C,A,T,T,T,G,T,A,T,T,T,G,C,A]]`, i.e. I want to preserve the sub-ranges. 

My next intuition was to create chunk over the full individual sequences to artificially create a situation where I am already dealing with ranges of ranges so that a later concat would only flatten the outer layer. However the following doesn't even compile:

```c++
    std::string s{"ACGTTTATGTTTACGT"};
    auto v1 = ranges::view::chunk(ranges::view::all(s), s.size());
    auto v2 = ranges::view::chunk(ranges::view::reverse(s), s.size());

    auto combined = ranges::view::concat(v1, v2);
```

1. What would be a correct solution to the problem?
2. Independent of the problem, why does the second example not build?

Thank you for your help!

**Comment by CaseyCarter** [comment]
Ranges in range-v3 (and standard C++, for that matter) are homogeneous: they are sequences of elements with a single type. `v1` and `v2` have different types, so there's no way to directly represent a range of `v1` and `v2` any more than we can have a `std::vector` whose first element is an `int` and second a `double`.

That said, solutions to do something like this will look a lot like solutions to the "How do I make a `vector` that can store both an `int` and a `double`?" A couple are:

* Make a `vector<variant<int, double>>` instead. You could do the same thing in range-v3, and it would be similarly awkward to use.

* Make a `vector<type_erasure>` instead, where `type_erasure` hides the differences between `int` and `double`. This is fairly simple to do with range-v3, which already includes an `any_view` type eraser for this sort of thing:
```c++
#include <iostream>
#include <string>
#include <range/v3/algorithm/equal.hpp>
#include <range/v3/view/all.hpp>
#include <range/v3/view/any_view.hpp>
#include <range/v3/view/concat.hpp>
#include <range/v3/view/reverse.hpp>
#include <range/v3/view/single.hpp>

int main() {
    std::string s{"ACGTTTATGTTTACGT"};

    auto v1 = ranges::view::all(s);
    auto v2 = ranges::view::reverse(s);

    std::cout
        << v1 << '\n'
        << v2 << '\n';

    // Our ranges have the same reference type (char&) and are both random access,
    // so we'll use any_random_access_view<char&> to type erase them.
    auto e1 = ranges::any_random_access_view<char&>(v1);
    RANGES_ASSERT(ranges::equal(v1, e1));

    auto e2 = ranges::any_random_access_view<char&>(v2);
    RANGES_ASSERT(ranges::equal(v2, e2));

    auto combined = ranges::view::concat(ranges::view::single(e1), ranges::view::single(e2));
    std::cout << combined << '\n';
}
```

**Comment by h-2** [comment]
Ah, thanks for your remarks. I had thought it would be something like that. Type erasure seems to do the trick.
And for "preserving" the sub-ranges, I just need to wrap them in `view::single`?

Btw. your example works fine in clang-3.9, but fails in g++6 and g++7 with
```
/home/mi/h4nn3s/devel/range-v3/include/range/v3/range_concepts.hpp:64:67: fatal error: template instantiation depth exceeds maximum of 10000 (use -ftemplate-depth= to increase the maximum)
                 using iterator_t = decltype(begin(std::declval<T&>()));
```

**Comment by CaseyCarter** [comment]
> And for "preserving" the sub-ranges, I just need to wrap them in `view::single`?

Yes, `view::single` is the easiest way to turn "thing" into "range of exactly thing". 

> Btw. your example works fine in clang-3.9, but fails in g++6 and g++7

Yes; it also works on clang trunk, GCC 4.9, and GCC 5. It's funny when an issue that isn't a bug report *still* results in me fixing a bug.

**Comment by h-2** [comment]
> Yes; it also works on clang trunk, GCC 4.9, and GCC 5. It's funny when an issue that isn't a bug report still results in me fixing a bug.

:laughing:

**Comment by h-2** [comment]
Hm, I really like working with ranges, but I still have some difficulties with (seemingly) basic things. I hope it's ok to reopen this and discuss. 
What I am trying to do is model a certain biological process called six-frame-translation. The details are not important, it boils down to transforming one sequence of characters in to six sequences of characters that have slightly different transformation rules each.
Every frame is a three-letter-to-one-letter conversion, with different clipping and the reverse frames undergo reversal and another transformation.
My intention should be clear from this program:
```c++
#include <iostream>
#include <range/v3/all.hpp>
#include <string>

char const translation_table[4][4][4] =
{
    { // a??
        { 'K', 'N', 'K', 'N' }, // aa?
        { 'T', 'T', 'T', 'T' }, // ac?
        { 'R', 'S', 'R', 'S' }, // ag?
        { 'I', 'I', 'M', 'I' }  // au?
    }, { // c??
        { 'Q', 'H', 'Q', 'H' }, // ca?
        { 'P', 'P', 'P', 'P' }, // cc?
        { 'R', 'R', 'R', 'R' }, // cg?
        { 'L', 'L', 'L', 'L' }  // cu?
    }, { // g??
        { 'E', 'D', 'E', 'D' }, // ga?
        { 'A', 'A', 'A', 'A' }, // gc?
        { 'G', 'G', 'G', 'G' }, // gg?
        { 'V', 'V', 'V', 'V' }  // gu?
    }, { // u??
        { '*', 'Y', '*', 'Y' }, // ua?
        { 'S', 'S', 'S', 'S' }, // uc?
        { '*', 'C', 'W', 'C' }, // ug?
        { 'L', 'F', 'L', 'F' }  // uu?
    }
};

uint8_t ord_value(char c)
{
    switch (c)
    {
        case 'c': case 'C': return 1;
        case 'g': case 'G': return 2;
        case 't': case 'T': case 'u': case 'U': return 3;
        default: return 0;
    }
}

int main()
{
    std::string s{"ACGTTTATGTTTACGT"};

    auto complement = [] (auto c)
    {
        switch (c)
        {
            case 'a': return 't';
            case 'A': return 'T';
            case 'c': return 'g';
            case 'C': return 'G';
            case 'g': return 'c';
            case 'G': return 'C';
            case 't': return 'a';
            case 'T': return 'A';
            default: return 'N';
        }
    };

    auto translate = [] (auto chunk_view)
    {
        if (chunk_view.size() < 3)
            return 'X';
        else
            return translation_table[chunk_view[0]][chunk_view[1]][chunk_view[2]];
    };

    ranges::any_random_access_view<char&> f[3];
    for (unsigned i : { 0, 1, 2 })
        f[i] = s | ranges::view::drop(i)
                 | ranges::view::transform(ord_value)
                 | ranges::view::chunk(3)
                 | ranges::view::transform(translate);

    ranges::any_random_access_view<char&> r[3];
    for (unsigned i : { 0, 1, 2 })
        r[i] = s | ranges::view::reverse
                 | ranges::view::transform(complement)
                 | ranges::view::drop(i)
                 | ranges::view::transform(ord_value)
                 | ranges::view::chunk(3)
                 | ranges::view::transform(translate);

    auto combined = ranges::view::concat(ranges::view::single(f[0]),
                                         ranges::view::single(f[1]),
                                         ranges::view::single(f[2]),
                                         ranges::view::single(r[0]),
                                         ranges::view::single(r[1]),
                                         ranges::view::single(r[2]));
    std::cout << combined << '\n';
    return 0;
}
```

I have incorporated your suggestions from above, but now I am facing the problem, that I cannot assign views later than creation (in the loops).
What would be the right way to do this? I seem not be able to put it all in one term, because I need to do type erasure in between, but I am also not able to "build up" a combined view iteratively...

I can imagine some solutions with repeat_n, and custom transforms that switches on the frame number, but this seems overly complicated and would negate the readability and clean design that ranges otherwise give.

Thanks for your help and for providing this library!

**Comment by ericniebler** [comment]
@h-2 can you sync and confirm that the problem is now fixed?

**Comment by CaseyCarter** [comment]
> I cannot assign views later than creation (in the loops).

You cannot assign those expressions to `any_random_access_view<char&>` because they are views with reference type `char` instead of `char&`. If you declare `f` and `r` to be arrays of `any_random_access_view<char>` the program should compile successfully.

**Comment by h-2** [comment]
> @h-2 can you sync and confirm that the problem is now fixed?

Yep, it's fixed!

> If you declare f and r to be arrays of any_random_access_view<char> the program should compile successfully.

Indeed, it does. Thanks!
