### ISSUE TITLE
view::enumerate issues with latest 1.0-beta commits?

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1141]
Hi!

The following code sample

```
#include "range/v3/view.hpp"

int main()
{
    ranges::view::indices( size_t( 100 ) ) | ranges::view::transform( []( size_t ){ return ""; } ) | ranges::view::enumerate;
}
```

doesn't compile with latest 1.0-beta branch. But it compiled fine before c9d18a1 commit.

Tested with clang 8.0 and gcc 8.2.1

**Comment by ericniebler** [comment]
It's a little tricky. My recent change gave `view::indices( size_t( 100 ) )` a user-defined difference type (`detail::diffmax_t`) capable as representing the range `[size_t(0), size_t(-1)]` as a signed integer(-like) type. (Previously, `distance( view::iota(size_t(0), size_t(-1)) )` would simply overflow and invoke undefined behavior.)

So, what's the problem with that?

Well, `view::enumerate` wants to pair each element with an unsigned index of the same size as the input range's difference type. For `view::indices( size_t( 100 ) ) | view::transform(...)`, the difference type is `detail::diffmax_t`. Fine, we could just create an iota view of the user-defined difference type, `iota_view<detail::diffmax_t>`, and just live with the fact that it's signed.

But the iota view has an iterator that _itself_ needs a difference type. It wants to pick one big enough to represent the largest range possible for the element type; that is `[diffmax_t(-big number), diffmax_t(+big number)]`. And that would need to be an integer-like type with _even greater_ precision than `diffmax_t`. The iota view doesn't know how to do that, so it fails to compile.

However, the `enumerate` view is special. The `iota_view<diffmax_t>` that `view::enumerate` constructs will never produce a number less than zero or greater than the maximum `diffmax_t`. So `diffmax_t` itself has enough bits to be usable as the difference type of `iota_view<diffmax_t>::iterator`.

I can solve this problem with a custom `index_view` that doesn't try to promote the index type when computing the difference type.

**Comment by voivoid** [comment]
The code sample unfortunately still fails to compile with clang 8.0 with -std=c++17 ( and compiles fine without -std=c++17 flag ).

Could be the clang problem?

<details><summary>Click to see the compilation error</summary>
<p>

```
In file included from ./main.cpp:1:
In file included from /home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/view.hpp:39:
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/view/enumerate.hpp:100:53: error: temporary of type 'view_interface<ranges::detail::index_view<ranges::detail::diffmax_t, ranges::detail::diffmax_t>,
      (ranges::cardinality)-3L>' has protected destructor
                return zip(detail::index_view<S, D>{}, all(static_cast<Rng &&>(rng)));
                                                    ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/invoke.hpp:118:20: note: in instantiation of function template specialization
      'ranges::view::enumerate_fn::operator()<ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)> >' requested here
            return static_cast<F&&>(f)(static_cast<Args&&>(args)...)
                   ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:617:27: note: expanded from macro 'CPP_auto_fun'
#define CPP_auto_fun(X) X CPP_AUTO_FUN_IMPL_
                          ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:618:47: note: expanded from macro 'CPP_AUTO_FUN_IMPL_'
#define CPP_AUTO_FUN_IMPL_(...) (__VA_ARGS__) CPP_AUTO_FUN_RETURNS_
                                              ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:620:5: note: expanded from macro 'CPP_AUTO_FUN_RETURNS_'
    CPP_AUTO_FUN_SELECT_RETURNS_(__VA_ARGS__,)(__VA_ARGS__)                     \
    ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:84:30: note: expanded from macro 'CPP_PP_CAT_'
#define CPP_PP_CAT_(X, ...)  X ## __VA_ARGS__
                             ^
<scratch space>:15:1: note: expanded from here
CPP_AUTO_FUN_RETURNS_CONST_1
^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:633:17: note: expanded from macro 'CPP_AUTO_FUN_RETURNS_CONST_1'
    __VA_ARGS__ CPP_AUTO_FUN_RETURNS_CONST_0                                    \
                ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/concepts.hpp:31:17: note: while substituting deduced template arguments into function template 'operator()' [with F =
      ranges::view::enumerate_fn &, Args = <ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)>>]
                invoke(static_cast<Fun &&>(fn), std::declval<Args>()...)
                ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/concepts.hpp:25:5: note: while substituting deduced template arguments into function template 'Requires_'
      [with Fun = ranges::view::enumerate_fn &, Args = (no value)]
    CPP_def
    ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:157:9: note: expanded from macro 'CPP_def'
        CPP_PP_DECL_DEF,                                                        \
        ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/concepts.hpp:25:5: note: while substituting deduced template arguments into function template 'impl' [with C_ = (no value)]
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:157:9: note: expanded from macro 'CPP_def'
        CPP_PP_DECL_DEF,                                                        \
        ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/concepts.hpp:25:5: note: in instantiation of member function 'ranges::InvocableConcept::Eval<ranges::view::enumerate_fn &,
      ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)> >::operator bool' requested here
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:157:9: note: expanded from macro 'CPP_def'
        CPP_PP_DECL_DEF,                                                        \
        ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/view/view.hpp:114:48: note: in instantiation of variable template specialization 'ranges::Invocable<ranges::view::enumerate_fn &,
      ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)> >' requested here
                requires ViewableRange<Rng> && Invocable<View &, Rng>)
                                               ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:606:22: note: expanded from macro 'CPP_fun'
#define CPP_fun(X) X CPP_FUN_IMPL_1_
                     ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:510:5: note: expanded from macro 'CPP_FUN_IMPL_1_'
    CPP_FUN_IMPL_REQUIRES                                                       \
    ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/functional/pipeable.hpp:102:30: note: while substituting deduced template arguments into function template 'pipe' [with Rng =
      ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)>, Vw = ranges::view::view<ranges::view::enumerate_fn> &]
            CPP_ret(decltype(pipeable_access::impl<Pipe>::pipe(
                             ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/concepts/concepts.hpp:493:5: note: expanded from macro 'CPP_ret'
    CPP_broken_friend_ret                                                       \
    ^
./main.cpp:5:100: note: while substituting deduced template arguments into function template 'operator|' [with Arg = ranges::transform_view<ranges::iota_view<unsigned long, unsigned long>, (lambda at ./main.cpp:5:71)>, Pipe =
      ranges::view::view<ranges::view::enumerate_fn>]
    ranges::view::indices( size_t( 100 ) ) | ranges::view::transform( []( size_t ){ return ""; } ) | ranges::view::enumerate;
                                                                                                   ^
/home/voivoid/Projects/advent-of-code-build-clang-release/thirdparties/src/get_rangev3/include/range/v3/view/interface.hpp:111:9: note: declared protected here
        ~view_interface() = default;
        ^
1 error generated.

```

</p>
</details>

**Comment by ericniebler** [comment]
I just downloaded and installed the clang-8.0.0 compiler, built and ran the `enumerate` test, and it works here. Not sure what the problem could be that you're seeing.

**Comment by voivoid** [comment]
Fixed. Great thanks for all your efforts!
