### ISSUE TITLE
"split | filter" doesn't compile in 0.11.0

### ISSUE THREAD

**Issue by DarthGandalf** [ericniebler/range-v3#1583]
clang 11.0.0 with libc++

```c++
std::string inp;
auto x = inp | ranges::views::split('\n') | ranges::views::filter([](const std::string& y) { return true; });
```
This works with range 0.10.0, but now shows error:
```
/home/somebody/advent-of-code/2020/day2.cpp:43:45: error: invalid operands to binary expression ('ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, ranges::single_view<char>>' and 'ranges::views::view_
closure<ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>>')                                                                                                                                            
                auto x = inp | ranges::views::split('\n') | ranges::views::filter([](const std::string& y) { return true; });                                                                                                                                                     
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/cstddef:94:17: note: candidate function not viable: no known conversion from 'ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, ranges::single_view<char>>' to 'std::byte' for 1st argument
constexpr byte  operator| (byte  __lhs, byte __rhs) noexcept
                ^
/usr/include/range/v3/view/any_view.hpp:65:24: note: candidate function not viable: no known conversion from 'ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, ranges::single_view<char>>' to 'ranges::category' for 1st argument
    constexpr category operator|(category lhs, category rhs) noexcept
                       ^
/usr/include/c++/v1/bitset:1071:1: note: candidate template ignored: could not match 'bitset' against 'split_view'
operator|(const bitset<_Size>& __x, const bitset<_Size>& __y) _NOEXCEPT
^
/usr/include/range/v3/view/view.hpp:110:35: note: candidate template ignored: constraints not satisfied [with Rng = ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, ranges::single_view<char>>, ViewFn = ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>]
            friend constexpr auto operator|(Rng && rng, view_closure<ViewFn> vw)
                                  ^
/usr/include/range/v3/view/view.hpp:109:21: note: because 'invocable_view_closure<ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>, ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, ranges::single_view<char> > >' evaluated to false
                    invocable_view_closure<ViewFn, Rng>)
                    ^
/usr/include/range/v3/detail/prologue.hpp:35:26: note: expanded from macro 'template'
    template<__VA_ARGS__ CPP_TEMPLATE_AUX_                                      \
                         ^
/usr/include/range/v3/view/view.hpp:76:9: note: because 'invocable<ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>, ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, ranges::single_view<char> > >' evaluated to false
        invocable<ViewFn, Rng> &&
        ^
/usr/include/range/v3/functional/concepts.hpp:43:9: note: because 'ranges::invocable__requires_<ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>, ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, ranges::single_view<char> > >' evaluated to false
        CPP_requires_ref(ranges::invocable_, Fun, Args...);
        ^
/usr/include/concepts/concepts.hpp:451:5: note: expanded from macro 'CPP_requires_ref'
    CPP_PP_CAT(NAME, _requires_)<__VA_ARGS__>
    ^
/usr/include/concepts/concepts.hpp:67:30: note: expanded from macro 'CPP_PP_CAT'
#define CPP_PP_CAT(X, ...)   CPP_PP_CAT_(X, __VA_ARGS__)
                             ^
/usr/include/concepts/concepts.hpp:66:30: note: expanded from macro 'CPP_PP_CAT_'
#define CPP_PP_CAT_(X, ...)  X ## __VA_ARGS__
                             ^
<scratch space>:118:1: note: expanded from here
invocable__requires_
^
/usr/include/range/v3/functional/concepts.hpp:39:13: note: because 'invoke((Fun &&)fn, std::declval<Args>()...)' would be invalid: no matching function for call to object of type 'const ranges::invoke_fn'
            invoke((Fun &&) fn, std::declval<Args>()...)
            ^
/usr/include/range/v3/view/view.hpp:135:35: note: candidate template ignored: could not match 'view_closure' against 'split_view'
            friend constexpr auto operator|(view_closure<ViewFn> vw, Pipeable pipe)
                                  ^
/usr/include/range/v3/view/view.hpp:153:13: note: candidate template ignored: constraints not satisfied [with Rng = ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, ranges::single_view<char>>, ViewFn = ranges::detail::bind_back_fn_<ranges::views::filter_base_fn, (lambda at /home/somebody/advent-of-code/2020/day2.cpp:43:69)>]
            operator|(Rng &&, view_closure<ViewFn> const &)    // ****** READ THIS *******
            ^
/usr/include/range/v3/view/view.hpp:151:42: note: because '!viewable_range<ranges::split_view<ranges::ref_view<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, ranges::single_view<char> > >' evaluated to false
                requires range<Rng> AND (!viewable_range<Rng>))// ************************
                                         ^
/usr/include/range/v3/detail/prologue.hpp:35:26: note: expanded from macro 'template'
    template<__VA_ARGS__ CPP_TEMPLATE_AUX_                                      \
                         ^
1 error generated.
```
