### ISSUE TITLE
Build errors under GCC 7.1 

### ISSUE THREAD

**Issue by koalization** [ericniebler/range-v3#659]
I tried to build this wonderful library under the newly released version of GCC. Steps I followed:

1. `cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/BUILDS/RANGE -DRANGE_V3_NO_HEADER_CHECK=1`
2. `make -j8`
 
While this works flawlessly with GCC 6.3.0 (both my own build on Ubuntu 16.04.2 and the one shipped with Debian Testing), it fails under GCC 7 (own builds of the stable version 7.1 on both Debian Testing/Ubuntu 16.04.2 and the pre-release version currently shipped with Fedora 26 (GCC 7.0.1), which is in turn a pre-release distribution). Here's the stderr:

```
/home/koalization/BUILDS/range-v3-master/test/getlines.cpp: In function 'int main()':
/home/koalization/BUILDS/range-v3-master/test/getlines.cpp:32:38: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     using Rng = decltype(getlines(sin));
                                      ^
/home/koalization/BUILDS/range-v3-master/test/getlines.cpp:32:38: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/getlines.dir/build.make:63: test/CMakeFiles/getlines.dir/getlines.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8968: test/CMakeFiles/getlines.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object test/CMakeFiles/multiple.dir/multiple2.cpp.o
[  4%] Linking CXX executable view_facade
[  4%] Built target view_facade
[  4%] Linking CXX executable bug474
[  4%] Built target bug474
[  4%] Linking CXX executable iterator_range
[  4%] Built target iterator_range
[  4%] Linking CXX executable index
[  4%] Built target index
[  4%] Linking CXX executable multiple
[  4%] Built target multiple
[  4%] Linking CXX executable view_adaptor
[  4%] Built target view_adaptor
[  4%] Linking CXX executable container_conversion
[  4%] Built target container_conversion
make: *** [Makefile:141: all] Error 2

```

**Comment by CaseyCarter** [comment]
Minimal Repro:
```c++
// Build with "g++ -Wstrict-aliasing -O2"
#include <fstream>

extern void f(std::istream&);

int main() {
    std::ifstream ifs;
    foo(ifs); // Fine
    using T = decltype(foo(ifs)); // triggers -Wstrict-aliasing
}
```
Looks like a compiler bug.

**Comment by koalization** [comment]
Thanks, I'll keep an eye on your bug report.

**Comment by CaseyCarter** [comment]
The patch avoids the problem in the OP, but fixes up a problem in view/replace_if.cpp by disabling diagnostics. Disabling the diagnostic in the test lets the tests compile but doesn't prevent the same diagnostic triggering for users. We need to investigate this other problem to be certain it's a false positive, and file a bug report / develop a proper library workaround.
