### ISSUE TITLE
range-v3 build errors with MSVC 14.25 

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1453]
range-v3 master fails to build with latest MSVC 14.25 ( released a few days ago, VS 16.5 ) due to multiple compiler errors

the issue can be reproduced with the following code
```
#include <range/v3/view/iota.hpp>
#include <range/v3/view/take.hpp>
#include <range/v3/view/reverse.hpp>

int main()
{
    using namespace ranges;
    auto rng5 = views::iota(10) | views::take(10) | views::reverse;
}
```

```
1>D:\Projects\range-v3\include\range/v3/utility/optional.hpp(579,1): error C2280: 'bool concepts::detail::operator &&(concepts::detail::boolean,bool)': attempting to reference a deleted function
1>D:\Projects\range-v3\include\concepts/concepts.hpp(751): message : see declaration of 'concepts::detail::operator &&'
1>D:\Projects\range-v3\include\concepts/concepts.hpp(751,25): message : 'bool concepts::detail::operator &&(concepts::detail::boolean,bool)': function was explicitly deleted
1>D:\Projects\range-v3\include\range/v3/utility/optional.hpp(909): message : see reference to class template instantiation 'ranges::optional<T>' being compiled
1>        with
1>        [
1>            T=ranges::counted_iterator<ranges::basic_iterator<ranges::iota_view<int,ranges::unreachable_sentinel_t>::cursor>,std::true_type,0>
1>        ]
1>D:\Projects\range-v3\include\range/v3/view/reverse.hpp(48): message : see reference to class template instantiation 'ranges::detail::non_propagating_cache<ranges::counted_iterator<ranges::basic_iterator<ranges::iota_view<int,ranges::unreachable_sentinel_t>::cursor>,std::true_type,0>,ranges::reverse_view<ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t>>>,true>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\type_traits(1610): message : see reference to class template instantiation 'ranges::reverse_view<ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t>>>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\type_traits(1610): message : while compiling class template member function 'ranges::reverse_view<ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t>>> std::_Invoker_functor::_Call<_Ty,ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t>>>(_Callable &&,ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t>> &&) noexcept(<expr>)'
1>        with
1>        [
1>            _Ty=ranges::views::reverse_fn,
1>            _Callable=ranges::views::reverse_fn
1>        ]
1>D:\Projects\range-v3\include\range/v3/functional/concepts.hpp(33): message : see reference to variable template 'const bool is_invocable_v<ranges::views::reverse_fn,ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t> > >' being compiled
1>D:\Projects\range-v3\include\range/v3/view/view.hpp(76): message : see reference to variable template 'const bool invocable<ranges::views::reverse_fn,ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t> > >' being compiled
1>D:\Projects\range-v3\include\range/v3/view/view.hpp(83): message : see reference to variable template 'const bool invocable_view_closure<ranges::views::reverse_fn,ranges::take_view<ranges::iota_view<int,ranges::unreachable_sentinel_t> > >' being compiled
1>D:\Projects\range-v3\include\concepts/concepts.hpp(869): message : see reference to function template instantiation 'auto ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>::operator ()<std::true_type>(std::true_type) const' being compiled
1>D:\Projects\range-v3\test\view\test.cpp(8): message : see reference to function template instantiation 'concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>::operator bool(void) noexcept const<true>' being compiled
1>D:\Projects\range-v3\include\concepts/concepts.hpp(792): message : see reference to function template instantiation 'concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>::operator bool(void) noexcept const<true>' being compiled
1>D:\Projects\range-v3\include\concepts/concepts.hpp(796,34): message : while evaluating constexpr function 'concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>::impl'
1>D:\Projects\range-v3\include\concepts/concepts.hpp(796,41): message : while evaluating constexpr function 'concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>::operator bool'
1>D:\Projects\range-v3\include\concepts/concepts.hpp(795): message : while compiling class template member function 'concepts::detail::and_<concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>,std::true_type>::operator bool(void) noexcept const'
1>D:\Projects\range-v3\test\view\test.cpp(8): message : see reference to class template instantiation 'concepts::detail::and_<concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>,std::true_type>' being compiled
1>D:\Projects\range-v3\include\range/v3/utility/optional.hpp(579,1): error C2088: '&&': illegal for struct
1>D:\Projects\range-v3\include\concepts/concepts.hpp(796,34): message : while evaluating constexpr function 'concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>::impl'
1>D:\Projects\range-v3\include\concepts/concepts.hpp(796,41): message : while evaluating constexpr function 'concepts::detail::and_<concepts::detail::boolean_<ranges::defer::<lambda_2ae2609f2938c514d772d4c416ac2f09>>,concepts::detail::boolean_<ranges::defer::<lambda_4b7ebeada7fee5bba52ad0d317e38301>>>::operator bool'
```
