### ISSUE TITLE
Compiler error GCC 

### ISSUE THREAD

**Issue by curtpm** [ericniebler/range-v3#651]
Using GCC 5.4.0 with Ubuntu 16.04
Range-V3 0.2.4

I'm trying to use a "ranges::span" but i just get thousands of these errors when compiling. 
using std=c++11 

```
range/v3/utility/concepts.hpp:117:69: error: template argument 1 is invalid
                         meta::bind_back<meta::quote<concepts::models>, Ts...>>>;
                                                                     ^
range-v3/src/lib/include/range/v3/utility/concepts.hpp:117:53: error: ‘concepts’ was not declared in this scope
                         meta::bind_back<meta::quote<concepts::models>, Ts...>>>;
```

**Comment by CaseyCarter** [comment]
[Simple span uses seem to be working fine on 16.04.2 with gcc 5.4.0 and c++11](https://wandbox.org/permlink/ax22JmlqeMvZ3JED). Can you post a minimal program that reproduces your problem?

**Comment by ericniebler** [comment]
Closing no repro.
