### PR TITLE
Use quote to avoid CWG1430 in meta::and_ and meta::or_ on clang 3.6 a…

### PR DESCRIPTION
**Pull request by CaseyCarter**
…nd 3.7

The gcc 4.9 problem seems to be more "interesting."

### CODE REVIEW

**Comment by ericniebler** [comment]
How odd. This works on the Travis version of clang-3.6.2, but fails with the clang-3.6.2 that I built locally. :-?

**Comment by ericniebler** [comment]
Does Travis clang use libc++ or libstdc++?

**Comment by ericniebler** [comment]
Ah, judging from the `install_libcxx.sh` script, Travis pulls down the *latest* libc++ sources and builds. It doesn't try to match the libc++ version to the clang version. @gnzlbg, can you comment?

I'm testing locally with the version of libc++ that shipped with clang-3.6.2, and it is failing hard in `std::is_function` while building alg.for_each.

```
Building CXX object test/algorithm/CMakeFiles/alg.for_each.dir/for_each.cpp.o
In file included from /Users/eniebler/Code/range-v3/test/algorithm/for_each.cpp:12:
In file included from /usr/local/clang-3.6.2/bin/../include/c++/v1/vector:265:
In file included from /usr/local/clang-3.6.2/bin/../include/c++/v1/__bit_reference:15:
In file included from /usr/local/clang-3.6.2/bin/../include/c++/v1/algorithm:625:
/usr/local/clang-3.6.2/bin/../include/c++/v1/type_traits:444:83: error: no matching function for call to '__source'
    : public integral_constant<bool, sizeof(__libcpp_is_function_imp::__test<_Tp>(__libcpp_is_function_imp::__source<_Tp>())) == 1>
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/clang-3.6.2/bin/../include/c++/v1/type_traits:449:14: note: in instantiation of template class 'std::__1::__libcpp_is_function<void () const, false>' requested here
    : public __libcpp_is_function<_Tp> {};
             ^
/Users/eniebler/Code/range-v3/include/range/v3/utility/invoke.hpp:105:33: note: in instantiation of template class 'std::__1::is_function<void () const>' requested here
                meta::if_c<std::is_function<F>::value, int> = 0>
                                ^
/Users/eniebler/Code/range-v3/include/range/v3/utility/invoke.hpp:106:28: note: while substituting prior template arguments into non-type template parameter [with F = void () const, Obj = S, First = S &, Rest = <>]
            constexpr auto operator()(F (Obj::*ptr), First && first, Rest &&... rest) const
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/eniebler/Code/range-v3/include/range/v3/utility/invoke.hpp:171:22: note: while substituting deduced template arguments into function template 'operator()' [with F = void () const, Obj = S, First = S &, Rest = <>, $4 = (no value)]
            decltype(invoke(std::declval<Fun>(), std::declval<Args>()...))>>
                     ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:140:9: note: during template argument deduction for class template partial specialization 'result_of<type-parameter-0-0 (type-parameter-0-1...), typename decltype(id<void>::impl(static_cast<list<decltype(invoke(std::declval<Fun>(), std::declval<Args>()...))> *>(nullptr)))::type>' [with Fun = void (S::*&)() const, Args = <S &>]
        using _t = typename T::type;
        ^
/Users/eniebler/Code/range-v3/include/range/v3/range_fwd.hpp:109:9: note: in instantiation of template type alias '_t' requested here
        using result_of_t = meta::_t<result_of<Sig>>;
        ^
/Users/eniebler/Code/range-v3/include/range/v3/utility/functional.hpp:205:17: note: in instantiation of template type alias 'result_of_t' requested here
                auto requires_() ->
                ^
/Users/eniebler/Code/range-v3/include/range/v3/utility/concepts.hpp:111:75: note: while substituting explicitly-specified template arguments into function template 'requires_'
                typename = decltype(gcc_bugs_bugs_bugs(&Concept::template requires_<Ts...>))>
                                                                          ^
/Users/eniebler/Code/range-v3/include/range/v3/utility/concepts.hpp:112:18: note: in instantiation of default argument for 'models_<void (S::*&)() const, S &, ranges::v3::concepts::Invocable>' required here
            auto models_(Concept *) ->
                 ^~~~~~~~~~~~~~~~~~~~~
/Users/eniebler/Code/range-v3/include/range/v3/utility/concepts.hpp:187:47: note: while substituting deduced template arguments into function template 'models_' [with Ts = (no value), Concept = ranges::v3::concepts::Invocable, $2 = (no value)]
              : meta::bool_<meta::_t<decltype(detail::models_<Ts...>(_nullptr_v<Concept>()))>::value>
                                              ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:1193:34: note: in instantiation of template class 'ranges::v3::concepts::models<ranges::v3::concepts::Invocable, void (S::*&)() const, S &>' requested here
        using strict_and = and_c<Bools::type::value...>;
                                 ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:646:32: note: in instantiation of template type alias 'strict_and' requested here
                    typename = C<Ts...>>
                               ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:647:34: note: in instantiation of default argument for 'try_<strict_and, ranges::v3::concepts::models<ranges::v3::concepts::Invocable, void (S::*&)() const, S &>, ranges::v3::concepts::models<ranges::v3::concepts::Invocable, void (S::*&)() const, S &>, ranges::v3::concepts::models<ranges::v3::concepts::Invocable, void (S::*&)() const, S &> >' required here
                result<C, Ts...> try_();
                                 ^~~~~~
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:667:49: note: while substituting deduced template arguments into function template 'try_' [with C = strict_and, Ts = (no value), $2 = (no value)]
            using defer_ = decltype(defer_if_{}.try_<C, Ts...>());
                                                ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:836:13: note: in instantiation of template type alias 'defer_' requested here
            using invoke = _t<detail::defer_<C, Ts...>>;
            ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:560:9: note: in instantiation of template type alias 'invoke' requested here
        using invoke = typename F::template invoke<Args...>;
        ^
/Users/eniebler/Code/range-v3/include/meta/meta.hpp:1021:17: note: in instantiation of template type alias 'invoke' requested here
                using invoke = invoke<F, invoke<compose<Gs...>, Ts>...>;
                ^
```

**Comment by ericniebler** [comment]
Of interest: https://reviews.llvm.org/D7573#724293

**Comment by CaseyCarter** [comment]
My local clang testing environment is traditionally "Whatever the latest Ubuntu installs for `clang++-<version>` and `libc++-dev`." While that certainly covers a sizable user base - Ubuntu has never synchronized libc++ with the clang version - I don't know what our typical clang user's environment looks like.

**Comment by gnzlbg** [comment]
> Ah, judging from the install_libcxx.sh script, Travis pulls down the latest libc++ sources and builds. It doesn't try to match the libc++ version to the clang version. @gnzlbg, can you comment?

Yes, this was by design. Back then there was no easy way to fetch different libc++ versions on travis. I've improved this in PR #600, and run into the exact same issue you have here (the fix is just very ad-hoc, since the libc++ version being installed are hardcoded and might not match the clang version, but that can be improved).
