### ISSUE TITLE
Can not compile actions::sort with projection on mingw64

### ISSUE THREAD

**Issue by silverqx** [ericniebler/range-v3#1657]
Following snippet compiles on gcc 10.2 on Linux, msvc and also clang 12, but it doesn't compile on msys2 mingw64:
```c++
QVector<QVariant> keys {10, 12, 9, 10, 12, 11, 11, 8, 8, 7};

using namespace ranges;
keys |= actions::sort(less {}, &QVariant::value<quint64>)
        | actions::unique;

qDebug() << keys;
```

The final error seems to be:
```
range\v3\action\action.hpp:108: error: no type named 'type' in 'struct std::enable_if<false, void>'
```

And whole error looks like this:
```
E:\c\tests_qt\console_app\console_app\main.cpp:35: error: no match for 'operator|=' (operand types are 'QVector<QVariant>' and 'concepts::return_t<ranges::actions::action_closure<ranges::composed<ranges::actions::action_closure<ranges::actions::unique_fn>, ranges::detail::bind_back_fn_<ranges::actions::sort_fn, ranges::less, long long unsigned int (QVariant::*)() const> > >, void>' {aka 'ranges::actions::action_closure<ranges::composed<ranges::actions::action_closure<ranges::actions::unique_fn>, ranges::detail::bind_back_fn_<ranges::actions::sort_fn, ranges::less, long long unsigned int (QVariant::*)() const> > >'})
E:/c/tests_qt/console_app/console_app/main.cpp: In function 'int main(int, char**)':
E:/c/tests_qt/console_app/console_app/main.cpp:35:10: error: no match for 'operator|=' (operand types are 'QVector<QVariant>' and 'concepts::return_t<ranges::actions::action_closure<ranges::composed<ranges::actions::action_closure<ranges::actions::unique_fn>, ranges::detail::bind_back_fn_<ranges::actions::sort_fn, ranges::less, long long unsigned int (QVariant::*)() const> > >, void>' {aka 'ranges::actions::action_closure<ranges::composed<ranges::actions::action_closure<ranges::actions::unique_fn>, ranges::detail::bind_back_fn_<ranges::actions::sort_fn, ranges::less, long long unsigned int (QVariant::*)() const> > >'})
     keys |= actions::sort(less {}, &QVariant::value<quint64>)
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             | actions::unique;
             ~~~~~~~~~
```
```
E:\c\tests_qt\console_app\console_app-builds\build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug\vcpkg_installed\x64-mingw-static\include\range\v3\view.hpp:22: In file included from E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/view.hpp:22,
In file included from E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/view.hpp:22,
                 from E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/all.hpp:25,
                 from E:/c/tests_qt/console_app/console_app/main.cpp:5:
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/view/any_view.hpp:90:26: note: candidate: 'constexpr ranges::category& ranges::operator|=(ranges::category&, ranges::category)'
     constexpr category & operator|=(category & lhs, category rhs) noexcept
                          ^~~~~~~~
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/view/any_view.hpp:90:26: note:   no known conversion for argument 1 from 'QVector<QVariant>' to 'ranges::category&'
```
```
E:\c\tests_qt\console_app\console_app-builds\build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug\vcpkg_installed\x64-mingw-static\include\range\v3\action\action.hpp:108: error: no type named 'type' in 'struct std::enable_if<false, void>'
In file included from E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/action.hpp:17,
                 from E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/all.hpp:17,
                 from E:/c/tests_qt/console_app/console_app/main.cpp:5:
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/action/action.hpp:108:35: note: candidate: 'template<class Rng, class ActionFn> constexpr concepts::return_t<Rng&, typename std::enable_if<((range<Rng> && invocable<ActionFn, Rng&>) && concepts::detail::CPP_true_fn(concepts::detail::Nil{})), void>::type> ranges::actions::action_closure_base_ns::operator|=(Rng&, ranges::actions::action_closure<ActionFn>)'
             friend constexpr auto operator|=(Rng & rng, action_closure<ActionFn> act) //
                                   ^~~~~~~~
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/action/action.hpp:108:35: note:   template argument deduction/substitution failed:
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/action/action.hpp: In substitution of 'template<class Rng, class ActionFn> constexpr concepts::return_t<Rng&, typename std::enable_if<((range<Rng> && invocable<ActionFn, Rng&>) && concepts::detail::CPP_true_fn(concepts::detail::Nil{})), void>::type> ranges::actions::action_closure_base_ns::operator|=(Rng&, ranges::actions::action_closure<ActionFn>) [with Rng = QVector<QVariant>; ActionFn = ranges::composed<ranges::actions::action_closure<ranges::actions::unique_fn>, ranges::detail::bind_back_fn_<ranges::actions::sort_fn, ranges::less, long long unsigned int (QVariant::*)() const> >]':
E:/c/tests_qt/console_app/console_app/main.cpp:36:24:   required from here
E:/c/tests_qt/console_app/console_app-builds/build-console_app-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/vcpkg_installed/x64-mingw-static/include/range/v3/action/action.hpp:108:35: error: no type named 'type' in 'struct std::enable_if<false, void>'
```

I know that the `proj` probably expects callable with one param or reference to data member and maybe other type of references, I'm posting this because I'm not sure what is the correct behavior, so if is correct that it compiles on msvc, gcc, clang or if it is a bug, simply it could indicate a bug if is correct this or that, I'm not a correct person to decide as I don't understand how it internally works.

Of course this works:
```c++
using namespace ranges;
keys |= actions::sort(less {}, [](auto v)
{
    return v.template value<quint64>();
})
        | actions::unique;
```
