### ISSUE TITLE
Regression: for_each on right value gsl::span fails in current head but worked in 0.10.0

### ISSUE THREAD

**Issue by FunMiles** [ericniebler/range-v3#1495]
The following code compiled under version 0.10.0 but does not anymore.
I have tried with g++ and clang++  on Linux and Mac OS X.

The error message is:
> /main.cpp:13:13: error: no matching function for call to object of type 'const ranges::views::for_each_fn'
   auto s = for_each(nodeToNode(0), [&](auto oldN) {
            ^~~~~~~~
/Users/michel/Development/Experiment/local/include/range/v3/view/for_each.hpp:46:36: note: candidate template ignored: substitution failure [with Rng = gsl::span<int,
      18446744073709551615>, Fun = (lambda at /Users/michel/Development/Experiment/RangeTest/main.cpp:13:37)]: no matching function for call to object of type
      'const view_closure<ranges::views::all_fn>'
            constexpr auto CPP_fun(operator())(Rng && rng, Fun fun)(
                                   ^
/Users/michel/Development/Experiment/local/include/concepts/concepts.hpp:595:53: note: expanded from macro 'CPP_fun'
#define CPP_fun(X) CPP_PP_IGNORE_CXX2A_COMPAT_BEGIN X CPP_FUN_IMPL_1_
                                                    ^
/Users/michel/Development/Experiment/local/include/range/v3/view/for_each.hpp:59:28: note: candidate function template not viable: requires single argument 'fun', but 2 arguments
      were provided
            constexpr auto operator()(Fun fun) const
                           ^
1 error generated.

```Cpp
#include <range/v3/all.hpp>
#include <gsl/gsl>

gsl::span<int> getspan(int i) {
   static int x[6] = {0,1,2,3,4,5};
   return {x};
}

int main() {
   using ranges::views::for_each;
   using ranges::views::ints;
   auto s = for_each(getspan(0), [&](auto oldN) {
                        return ints(oldN, oldN*3);
                });

   return 0;
}
```

**Comment by marehr** [comment]
I think the problem is that ranges does not know that your `gsl::span` is a view. It knows that you have a range, but a range is not indistinguishable from a view, so you have to declare it as a view.
See https://eel.is/c++draft/range.view#4

This works:
```c++
#include <range/v3/all.hpp>
#include <gsl/gsl>

gsl::span<int> getspan(int i) {
   static int x[6] = {0,1,2,3,4,5};
   return {x};
}

namespace ranges
{
template<typename T>
inline constexpr bool enable_view<gsl::span<T>> = true;
} // namespace ranges


int main() {
   using ranges::views::for_each;
   using ranges::views::ints;
   auto s = for_each(getspan(0), [&](auto oldN) {
                        return ints(oldN, oldN*3);
                });

   return 0;
}
```

https://godbolt.org/z/wuXBH_

**Comment by FunMiles** [comment]
@marehr Thanks. That's helpful. Still surprising to have a breaking change swept up like this. It will force me to reorganize my includes since I need to have that definition once but available wherever I use the range library (I am a big user of gsl::span).

**Comment by ericniebler** [comment]
I did not make this change lightly. I made it to conform to C++20's `std::ranges`. That was a change made by the C++ Committee just under the wire, and I was opposed. We don't all get what we want. :-)
