### ISSUE TITLE
Conversion to a 2D container fails

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#1544]
Hi everyone, the code snippet from #1308 is failing to compile in v0.11.0 in both `clang++` and `g++`:
```c++
#include <range/v3/all.hpp>
#include <vector>
namespace rgv = ranges::views;
int main()
{
    {
        // 2D view fails.
        const std::vector<std::vector<int>> data;
        auto data_view = rgv::transform(data, rgv::all);
        ranges::to<std::vector<std::vector<int>>>(data_view);
    }
    {
        // 1D view is ok.
        const std::vector<int> data;
        auto data_view = rgv::all(data);
        ranges::to<std::vector<int>>(data_view);
    }
}
```
`clang++ test.cpp` produces:
```
test.cpp:10:9: error: no matching function for call to 'to'
        ranges::to<std::vector<std::vector<int>>>(data_view);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/range/v3/range/conversion.hpp:431:14: note: candidate function template not viable: no known conversion from 'ranges::transform_view<ranges::ref_view<const std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > >, ranges::views::view_closure<ranges::views::all_fn> >' to 'detail::to_container' for 1st argument
        auto to(RANGES_HIDDEN_DETAIL(detail::to_container = {}))
             ^
/usr/include/range/v3/range/conversion.hpp:441:14: note: candidate template ignored: requirement 'detail::convertible_to_cont<ranges::transform_view<ranges::ref_view<const std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > >, ranges::views::view_closure<ranges::views::all_fn> > &, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > >' was not satisfied [with Cont = std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >, Rng = ranges::transform_view<ranges::ref_view<const std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > >, ranges::views::view_closure<ranges::views::all_fn> > &, CPP_true = true, $3 = 0]
        auto to(Rng && rng) -> Cont
             ^
/usr/include/range/v3/range/conversion.hpp:458:14: note: candidate template ignored: could not match 'initializer_list' against 'transform_view'
        auto to(std::initializer_list<T> il) -> Cont
             ^
/usr/include/range/v3/range/conversion.hpp:412:14: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'ContT'
        auto to(RANGES_HIDDEN_DETAIL(detail::to_container = {}))
             ^
/usr/include/range/v3/range/conversion.hpp:423:14: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'ContT'
        auto to(Rng && rng) -> ContT<range_value_t<Rng>>
             ^
/usr/include/range/v3/range/conversion.hpp:451:14: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'ContT'
        auto to(std::initializer_list<T> il) -> ContT<T>
             ^
1 error generated.
```
Is it now intentional that 2D ranges cannot be converted to a container?
Thank you.

```
clang version 10.0.1
gcc version 10.1.0 (GCC)
```

**Comment by johelegp** [comment]
`ranges::to_vector` works fine: https://godbolt.org/z/75n9jj.

**Comment by ericniebler** [comment]
Interestingly, although

```c++
ranges::to<std::vector<std::vector<int>>>(v);
```

fails,

```c++
v | ranges::to<std::vector<std::vector<int>>>;
```

succeeds.
