### ISSUE TITLE
0.9.x fails to build with clang 9.0-rc5

### ISSUE THREAD

**Issue by berolinux** [ericniebler/range-v3#1321]
Building range-v3 0.9.1 or 0.9.0 with clang 9.0 results in:

```
ld: error: duplicate symbol: ranges::detail::_is_integer_like_<ranges::detail::diffmax_t>
>>> defined in test/CMakeFiles/multiple.dir/multiple1.cpp.o
>>> defined in test/CMakeFiles/multiple.dir/multiple2.cpp.o
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

```

0.5.0 is ok.

**Comment by mlund** [comment]
I have the same issue with anaconda installed clang9 on macos 10.14.6:
```
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin18.7.0
```

**Comment by oliverdain** [comment]
Apple is now several versions past clang 9/Xcode 11.3. Is there any rough timeline for a fix (e.g. is anyone working on it)?

**Comment by oliverdain** [comment]
This isn't OSX specific. I'm now seeing this with newer versions of clang (clang 10) on Linux as well.
